import type { Metadata } from "next"
import "./globals.scss"
import "quill/dist/quill.snow.css"

import { Roboto_Mono } from "next/font/google"
const font = Roboto_Mono({
  variable: "--roboto_mono-font",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${font.variable}  antialiased`}>{children}</body>
    </html>
  )
}
