import { generateTagger } from "@/app/lib/nlp/nlp.utils";

/**
 * Singleton instance of tagger generated by `generateTagger` utility.
 * Used for tagging and NLP tasks throughout the application.
 */
export const tagger = generateTagger();
