import { generateTagger } from "@/app/lib/nlp/nlp.utils";
import { BrillPOSTagger } from "natural";

/**
 * Singleton instance of tagger generated by `generateTagger` utility.
 * Used for tagging and NLP tasks throughout the application.
 */
let singleton:BrillPOSTagger;

export const getTaggerSingleton = () => {
   if (!singleton) singleton = generateTagger();
  return singleton;
}
