import { BrillPOSTagger } from "natural";
import nlp from "compromise"
/**
 * Singleton instance of tagger generated by `generateTagger` utility.
 * Used for tagging and NLP tasks throughout the application.
 */
export const getTaggerSingleton = () => {
  return nlp
}
